# Generated by Django 3.2.6 on 2021-10-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=7, verbose_name='end date'),
            preserve_default=False,
        ),
    ]
